### ISSUE TITLE
FAR-MARS Lady Elizabeth Control System Executable 

### ISSUE THREAD

**Issue by christopherwj** [SDSURocketProject/FAR-MARS#12]
Scope of Issue: 

 "Lady Elizabeth Control Software" for the FAR/MARS rocket crashes when choosing minimized option. (v0.1.0).

Description of issue:

 When using windows.exe and exploring the standard file, edit, tools, drop downs there is a drop down labeled "Window". This drop down has two options to select within it. "Fullscreen" and "minimize". While running the executable has a thumbnail in the windows taskbar, however when minimizing through this drop down option the whole program disappears from both the screen and the task bar. The process also no longer exists in windows task manager, or in the system icon tray. Also there aren't any crash prompts that appear as a result. 

Host Machine:
OS: Windows Pro 10 build 1803 (64-bit)

Run time recommendations: Windows defender will flag it as a virus and not allow you to open it unless you click "more info">"run anyway".

**Comment by alefir** [comment]
Closing because fullscreen and minimize buttons no longer exist

**Comment by christopherwj** [comment]
That's one way to fix the issue, lol. Are you still working within the Qt framework?

**Comment by alefir** [comment]
The GUI still uses Qt5
