### ISSUE TITLE
Random spikes in helium readout.

### ISSUE THREAD

**Issue by waltoncade** [SDSURocketProject/FAR-MARS#15]
A periodic spike in pressure can be seen on the Helium channel on the PCB. This only happens when pressures are relatively constant.

**Comment by alefir** [comment]
Can you add examples?

**Comment by waltoncade** [comment]
[
![wrong_1](https://user-images.githubusercontent.com/26453366/52692460-d291c580-2f18-11e9-99bf-0ef6ace29a0b.png)
![wrong_2](https://user-images.githubusercontent.com/26453366/52692461-d291c580-2f18-11e9-9d5c-6c7ab5ab88e3.png)

](url)

**Comment by alefir** [comment]
Closing because error fixed sometime around [b644c16a26647ab3e9bc7db6e73e64c76da864d5]
